### ISSUE TITLE
fs.existsSync is not a function

### ISSUE THREAD

**Issue by ubmarco** [mahmut-aksakalli/arxml-viewer#2]
Hi,
thanks for this tool and the work you put into it.
After cloning and running
```
npm install
npm run serve
```
and opening the app in Firefox, I just get a blank page.
The console says `fs.existsSync is not a function`.
![image](https://user-images.githubusercontent.com/839934/155687505-d2a32e92-674e-47c9-82ca-5a9f45f83418.png)

Any clues?

**Comment by mahmut-aksakalli** [comment]
Hi Marco,

it does not work on web browser. You need electronjs to run it as desktop app. Please, check readme on project.

npm install
npm run electron:serve

**Comment by ubmarco** [comment]
Oh, I was just looking into the package.json and found `serve`.
Thanks it works now!
